In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib tk

In [4]:
### f is float in GHz
from scipy.constants import c
def leng(f):
    f2=f*1e9 ## to GHz
    eff=(11.9+1)/2
    le=c/(4*np.sqrt(eff)*f2)
    le=le*1e3 # to milimeters
    return le
leng(5.0004)

5.901686118161942

In [3]:
df=pd.read_csv('data_analysis.txt', skiprows=15, sep='\s+')
df

,Sim,Estado,FreqA(GHz),FreqB(GHz),LongA(mm),LongB(mm),FreA,QcA,QcB,Estado.1
0,5.50000,no,4.9803,5.4030,5.013818,5.408361,5.0,NaN,NaN,NaN
1,5.40000,no,4.9803,5.3374,5.013818,5.568100,5.0,NaN,NaN,NaN
2,5.30000,no,4.9803,5.1880,5.013818,5.675200,5.0,NaN,NaN,NaN
3,5.20000,no,4.9803,5.0841,5.013818,5.786400,5.0,NaN,NaN,NaN
4,5.10000,no,4.9989,5.0403,5.013818,5.843700,5.0,NaN,NaN,NaN
5,5.01000,no,4.9809,5.0327,5.013818,5.878600,5.0,NaN,NaN,NaN
6,5.02000,okd,4.9809,4.9974,5.013818,5.890400,5.0,NaN,NaN,NaN
7,5.05000,okd,4.9809,5.0051,5.013818,5.890400,5.0,NaN,NaN,NaN
8,5.00500,ok,4.9888,5.0450,5.013818,5.896300,5.0,NaN,NaN,NaN
9,5.00050,ok,4.9917,5.0018,5.013818,5.901600,5.0,NaN,NaN,NaN
10,5.00005,ok,5.0113,5.0137,5.013818,5.902100,5.0,NaN,NaN,NaN
11,5.00001,dok,5.0027,5.0794,5.013818,5.902146,5.0,NaN,NaN,NaN
12,5.00000,ok,4.9855,5.0796,5.013818,5.902158,5.0,NaN,NaN,NaN
13,4.99990,ok,5.0169,5.0307,5.013818,5.902276,5.0,NaN,NaN,NaN
14,4.99900,ok,5.0027,5.0096,5.013818,5.903339,5.0,NaN,NaN,NaN
15,4.99000,ok,5.0083,4.9750,5.013818,5.913986,5.0,NaN,NaN,NaN
16,4.90000,ok,5.0797,4.9136,5.013818,6.022610,5.0,NaN,NaN,NaN
17,4.80000,no,5.0450,4.8000,5.913986,6.148082,5.0,NaN,NaN,NaN

In [81]:
df=pd.read_csv('data_analysis.txt', skiprows=15, sep='\s+')
fig,ax=plt.subplots()
ax.plot(1/df['LongB(mm)'],df['FreqB(GHz)'],'-o', label='FreqB')
ax.plot(1/df['LongB(mm)'], df['FreqA(GHz)'],'-o', label='FreqA')
ax.plot(1/leng(df['Sim']),df['Sim'], '--', label='f_B')
ax.plot(1/leng(df['Sim']),df['FreA'], '--', label='f_A')
ax.set_xlabel('$1/L_B$')
ax.set_ylabel('$f_0$')
plt.legend()

In [ ]:
fre